version: 0.0
os: linux
files:
  - source: /
    destination: /home/ec2-user
hooks:
  AfterInstall:
    - location: fix_previleges.sh
      timeout: 300
      runas: ubuntu
  ApplicationStop:
    - location: stop_application.sh
      timeout: 300
      runas: ubuntu
  ApplicationStart:
    - location: start_application.sh
      timeout: 300
      runas: ubuntu